// challenge.js - 第一部分 (1-60题)
const challengeBank = [
    // === 模块一：网络发展史与标准化（来自 PPT原题.pdf） ===
    { type: "single", title: "【PPT原题】1973年，Metcalfe的博士论文提出了下面哪个技术？", options: ["SMTP protocol", "Ethernet", "TCP/IP", "DNS"], answer: [1] },
    { type: "single", title: "【PPT原题】ARPANET正式采用TCP/IP协议是哪一年？", options: ["1969年", "1983年", "1993年", "2000年"], answer: [1] },
    { type: "single", title: "【PPT原题】中国下一代互联网示范工程CNGI首次在国际上研制成功的是什么？", options: ["大型纯IPv6互联网主干网CNGI-CERNET2", "大型纯IPv4互联网主干网", "混合IPv4/IPv6互联网主干网", "无线互联网主干网"], answer: [0] },
    { type: "multi", title: "【PPT原题】以下哪些是互联网标准化组织的组成部分？", options: ["ISOC", "IAB", "IETF", "IESG"], answer: [0, 1, 2, 3] },
    { type: "single", title: "TCP/IP协议簇中，负责将数据包从源主机路由到目的主机的层次是？", options: ["网络接口层", "网际层 (Internet)", "传输层", "应用层"], answer: [1] },
    { type: "judge", title: "RFC（Request For Comments）是互联网标准的主要发布形式，但并不是所有的RFC都是互联网标准。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "RFC（Request For Comments）是互联网标准的主要发布形式，但并不是所有的RFC都是标准。", options: ["正确", "错误"], answer: [0] },

    // === 模块二：IPv6 报头结构与特征（第1-2讲 & 原题） ===
    { type: "single", title: "【PPT原题】在IPv6报头中，哪个字段的作用类似于IPv4的TTL（生存时间）字段？", options: ["Traffic Class", "Flow Label", "Next Header", "Hop Limit"], answer: [3] },
    { type: "single", title: "【PPT原题】IPv6基本报头的长度是固定的，它是多少字节？", options: ["20", "40", "60", "80"], answer: [1] },
    { type: "single", title: "IPv6报头中的 Next Header 字段取值为 58 时，代表紧跟其后的是？", options: ["TCP", "UDP", "ICMPv6", "路由扩展头"], answer: [2] },
    { type: "single", title: "IPv6基本报头中用于支持QoS并标识同一流的分组字段是？", options: ["Traffic Class", "Flow Label", "Next Header", "Hop Limit"], answer: [1] },
    { type: "single", title: "IPv6报头中的 Traffic Class 字段长度是多少位？", options: ["4", "8", "12", "20"], answer: [1] },
    { type: "multi", title: "IPv6报头相比IPv4报头，取消了哪些字段？", options: ["Checksum", "Header Length", "Identification", "Flags"], answer: [0, 1, 2, 3] },
    { type: "judge", title: "IPv6基本报头中不再包含选项（Options）字段，而是通过扩展报头来实现。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "IPv6分片扩展报头中，用于标识是否为最后一个分片的标志位是？", options: ["M位 (More Fragment)", "L位", "T位", "O位"], answer: [0] },
    { type: "single", title: "IPv6基本报头中，Payload Length（有效载荷长度）字段的长度是多少位？", options: ["8", "16", "24", "32"], answer: [1] },

    // === 模块三：IPv6 地址技术（第2讲 & 原题） ===
    { type: "multi", title: "【PPT原题】下面这个IPv6地址：0001:0123:0000:0000:ABCD:0000:0000:0001/96，哪些表示方法是正确的？", options: ["1:123:0:0:abcd::1/96", "1:123::abcd::1/96", "1:123::abcd:0:0:1/96", "上面三个全对"], answer: [0, 2] },
    { type: "single", title: "IPv6地址格式中，前8位固定为 FF 的地址属于哪种类型？", options: ["单播", "任播", "组播", "链路本地"], answer: [2] },
    { type: "single", title: "IPv6链路本地地址（Link-Local Address）的前缀是？", options: ["FC00::/7", "FE80::/10", "FF00::/8", "2000::/3"], answer: [1] },
    { type: "single", title: "被请求节点组播地址（Solicited-Node Address）的前缀部分是？", options: ["FF02::1", "FF02::1:FF00:0/104", "FF02::2", "FE80::1"], answer: [1] },
    { type: "single", title: "IPv6地址中，用于标识同一站点内唯一标识的地址类型是（已废弃但考点常见）？", options: ["全球单播地址", "链路本地地址", "站点本地地址 (Site-Local)", "组播地址"], answer: [2] },
    { type: "judge", title: "IPv6任播（Anycast）地址与全球单播地址共享相同的地址空间，无法从地址格式上区分。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "IPv6地址 2001:0db8::8:800:200c:417a 中，:: 替换了多少位的零？", options: ["16", "32", "48", "64"], answer: [1] },
    { type: "judge", title: "IPv6地址中，双冒号“::”在一个地址中只能出现一次。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "IPv6分片报头中，M位为0表示什么？", options: ["这是第一个分片", "后面还有更多分片", "这是最后一个分片", "不可分片"], answer: [2] },

    // === 模块四：NDP 与 SLAAC 自动配置（第3讲 & 原题） ===
    { type: "single", title: "【PPT原题】当主机应该使用“仅SLAAC”这个可选项时，标记（Flags）的设置是什么样的？", options: ["A=1, M=0, O=0", "A=1, M=1, O=0", "A=1, M=0, O=1", "A=0, M=0, O=0"], answer: [0] },
    { type: "single", title: "NDP协议中，用于实现IPv4中ARP地址解析功能的报文组合是？", options: ["RS/RA", "NS/NA", "Redirect", "Echo Request"], answer: [1] },
    { type: "single", title: "RA（路由器通告）报文中的 M 标记位（Managed Address Config）设置为 1 表示？", options: ["使用SLAAC获取地址", "通过有状态DHCPv6获取地址", "通过无状态DHCPv6获取DNS", "禁用地址分配"], answer: [1] },
    { type: "single", title: "主机在生成一个IPv6地址后，必须通过什么过程来确保链路上没有地址冲突？", options: ["SLAAC", "DHCPv6", "DAD (重复地址检测)", "Neighbor Discovery"], answer: [2] },
    { type: "single", title: "ICMPv6 消息类型中，Type=133 对应哪种 NDP 报文？", options: ["RS (路由器请求)", "RA (路由器通告)", "NS", "NA"], answer: [0] },
    { type: "single", title: "NDP协议规定所有NDP报文的跳数限制（Hop Limit）必须为？", options: ["1", "64", "128", "255"], answer: [3] },
    { type: "judge", title: "在SLAAC中，主机生成的临时地址（Privacy Extensions）主要是为了防止用户的MAC地址暴露。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "RA报文中的 A 标记位（Autonomous Address Config）为 1 表示？", options: ["支持无状态地址配置", "必须找DHCP服务器", "地址有效期限无限", "禁用此地址"], answer: [0] },
    { type: "judge", title: "主机只有在收到 RA 报文后，才能开始进行无状态地址配置。", options: ["正确", "错误"], answer: [1] },
    { type: "single", title: "被请求节点组播地址的前缀是？", options: ["FE80::/10", "FF02::1:FF00:0/104", "FF02::1", "FF02::2"], answer: [1] },

    // === 模块五：路由基础与 DV 算法（第4讲 & 原题） ===
    { type: "single", title: "【PPT原题】在路由选择中启用自动汇总可能导致哪些问题？", options: ["浪费带宽", "部分ICMP消息丢失", "路由表过大", "安全性降低"], answer: [1] },
    { type: "single", title: "距离矢量（DV）协议中，路由器解决“无限计数”问题的机制不包括？", options: ["水平分割", "毒性逆转", "最大跳数限制", "Dijkstra算法"], answer: [3] },
    { type: "single", title: "在距离矢量算法中，路由器定期向谁发送路由更新？", options: ["仅相邻邻居", "全网所有节点", "仅指定路由器", "仅在拓扑变化时发送"], answer: [0] },
    { type: "judge", title: "静态路由的优先级在华为设备上默认为 60，值越小优先级越高。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "默认路由的掩码表示形式是？", options: ["/0", "/128", "/32", "/64"], answer: [0] },
    { type: "judge", title: "距离矢量协议（如RIP）的主要问题是收敛速度较慢，容易产生环路。", options: ["正确", "错误"], answer: [0] },

    // === 模块六：OSPF 运行机制（第5讲 & 原题计算） ===
    { type: "single", title: "【PPT原题】正常情况下，每个路由器根据LSP/LSA构造出来的图（Graph）是一样的吗？", options: ["是", "不是", "不一定"], answer: [0] },
    { type: "single", title: "【PPT原题】上题中，从R1到达目的网络10.1.5.0和10.1.3.0，所需要的代价（开销）分别是多少？", options: ["9, 14", "7, 14", "9, 20", "7, 22"], answer: [0] },
    { type: "single", title: "【PPT原题】新路由器R部署并和DR交换了全部DD报文后，接下来的一个报文最有可能是？", options: ["Hello", "DD", "LSR", "LSU", "LSAck"], answer: [2] },
    { type: "single", title: "【PPT原题】在OSPFv3中，Router-ID相比OSPFv2有什么变化？", options: ["Router-ID不再包含地址信息", "Router-ID长度变为64位", "Router-ID不再需要配置", "Router-ID被取消"], answer: [0] },
    { type: "single", title: "OSPF协议中，状态机处于什么状态表示已完成 DR/BDR 选举？", options: ["Init", "2-Way", "ExStart", "Full"], answer: [1] },
    { type: "single", title: "OSPFv3 中用于传递“区域内路由前缀信息”的新增 LSA 类型是？", options: ["Type 1", "Type 8", "Type 9 (Intra-Area-Prefix-LSA)", "Type 5"], answer: [2] },
    { type: "single", title: "OSPFv3 中，Link-LSA (Type 8) 的主要作用是？", options: ["通告链路本地地址", "通告外部路由", "选举ABR", "在区域间同步汇总路由"], answer: [0] },
    { type: "single", title: "OSPF 协议在 IP 报头中的协议号是？", options: ["6", "17", "58", "89"], answer: [3] },
    { type: "multi", title: "OSPF 建立毗邻关系需要满足哪些条件？", options: ["Hello/Dead 间隔一致", "Area ID 一致", "认证信息一致", "掩码一致 (广播网)"], answer: [0, 1, 2, 3] },
    { type: "single", title: "OSPFv3 的 LSA 报头中 LS Type 字段长度是？", options: ["8位", "16位", "24位", "32位"], answer: [1] },
    { type: "single", title: "在 OSPF 广播网中，DR 和 BDR 监听的 IPv6 组播地址是？", options: ["FF02::5", "FF02::6", "FF02::9", "FF02::D"], answer: [1] },
    { type: "single", title: "OSPF 状态机中，正在交换 LSA 摘要以同步数据库的状态是？", options: ["Exchange", "Loading", "ExStart", "Full"], answer: [0] },
    { type: "judge", title: "在 OSPF 中，建立邻居关系（Neighbor）并不等同于建立邻接关系（Adjacency）。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "OSPFv3 明确地提供了对多实例（Multi-instance）的支持，主要用于？", options: ["一条链路上运行多个OSPF进程", "支持多个IPv4地址", "加速SPF计算", "替代BGP"], answer: [0] },
    { type: "judge", title: "OSPFv3 使用链路本地地址作为协议分组发送的源地址。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "OSPF 区域 0 的主要作用是？", options: ["连接外部自治系统", "负责非骨干区域间的路由转发", "仅用于承载虚连接", "防止 LSA 扩散"], answer: [1] },
    { type: "single", title: "OSPFv3 协议中，LSA 类型取值 0x2001 代表？", options: ["Router-LSA", "Network-LSA", "Link-LSA", "Intra-Area-Prefix-LSA"], answer: [0] },
    { type: "single", title: "在 OSPF 广播网选举中，若优先级（Priority）相同，则如何比较？", options: ["比较MAC地址，大者优", "比较Router ID，大者优", "比较接口IP，小者优", "随机选择"], answer: [1] },
    { type: "judge", title: "OSPF 是一种基于 Dijkstra 算法的链路状态协议。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "OSPFv3 的 LS Type 字段中包含 U/S2/S1 位，其中 S1/S2 用于定义？", options: ["泛洪范围", "LSA优先级", "报文序列号", "校验和"], answer: [0] },
    { type: "judge", title: "在 OSPFv3 中，AS-External-LSA（Type 5）可以在整个自治系统内泛洪。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "OSPFv3 支持多实例运行。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "OSPFv3 使用链路本地地址作为源地址。", options: ["正确", "错误"], answer: [0] },

// === 模块七：BGP 协议深度细节（第6讲 & 补充考点） ===
    { type: "single", title: "BGP 协议使用的传输层协议及端口号是？", options: ["UDP 179", "TCP 179", "TCP 89", "ICMPv6 58"], answer: [1] },
    { type: "single", title: "BGP 选路原则中，Preferred-Value（权重）属性的特点是？", options: ["AS间传递", "仅在本地有效", "越大越优先", "B和C均对"], answer: [3] },
    { type: "single", title: "BGP 中用于在 AS 内部防止路由环路的机制是？", options: ["AS_Path检测", "IBGP水平分割", "设置Hold Time", "触发更新"], answer: [1] },
    { type: "single", title: "BGP 选路原则中，AS_Path 属性的比较规则是？", options: ["AS_Path 越长越优", "AS_Path 越短越优", "选择不包含 AS_Path 的路径", "随机选择"], answer: [1] },
    { type: "single", title: "BGP 状态机中，发送 Open 报文后进入的状态是？", options: ["Idle", "Connect", "OpenSent", "Established"], answer: [2] },
    { type: "single", title: "BGP 的 Local_Preference 属性主要用于？", options: ["告知邻居AS如何进本AS", "在AS内部选择出口路径", "防止环路", "标记路由起源"], answer: [1] },
    { type: "multi", title: "下列 BGP 路径属性中，属于公认必遵（Well-known Mandatory）的是？", options: ["Origin", "AS_Path", "Next_Hop", "MED"], answer: [0, 1, 2] },
    { type: "multi", title: "BGP 的可选非过渡（Optional Non-transitive）属性包括？", options: ["MED", "Aggregator", "Community", "Originator_ID"], answer: [0, 3] },
    { type: "judge", title: "BGP 邻居关系建立后，如果不定期发送 Keepalive 报文，邻居关系会超时中断。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "BGP 的 Update 报文可以一次撤销多条路由，但只能通告一条路径属性相同的路由。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "BGP 状态机中，Connect 状态下如果 TCP 连接建立失败，将进入哪个状态？", options: ["Idle", "Active", "OpenSent", "Established"], answer: [1] },


    // === 模块八：组播技术（第7-8讲 & SDN.pdf & 原题） ===
    { type: "single", title: "【PPT原题】IPv6组播地址映射MAC地址时，其前缀固定为什么？", options: ["01:00:5E", "33:33", "FF:02", "00:00:0C"], answer: [1] },
    { type: "single", title: "【PPT原题】FF02::1 对应的映射组播MAC地址是？", options: ["33:33:00:00:00:01", "33:33:FF:00:00:01", "01:00:5E:00:00:01", "33:33:00:00:00:02"], answer: [0] },
    { type: "single", title: "【SDN.pdf】PIM-DM（密集模式）采用的是哪种模型？", options: ["推 (Push) 模型", "拉 (Pull) 模型", "资源预留模型", "标签转发模型"], answer: [0] },
    { type: "single", title: "【SDN.pdf】PIM-SM（稀疏模式）建立共享树（RPT）的核心节点是？", options: ["DR", "RP (汇聚点)", "ASBR", "组播源"], answer: [1] },
    { type: "single", title: "IPv6 组播地址格式中，Flags 字段的 T 位为 1 代表什么？", options: ["永久地址", "临时地址", "含RP的地址", "本地地址"], answer: [1] },
    { type: "single", title: "用于在 IPv6 主机与路由器之间管理组播成员关系的协议是？", options: ["IGMP", "MLD", "PIM", "BGP"], answer: [1] },
    { type: "single", title: "组播路由中 RPF 检查的主要目的是？", options: ["寻找最短路径", "防止组播数据环路", "选举DR", "发现邻居"], answer: [1] },
    { type: "multi", title: "组播地址范围（Scope）字段中，5 代表什么范围？", options: ["节点本地", "链路本地", "站点本地", "全球范围"], answer: [2] },
    { type: "judge", title: "BIERv6 转发组播数据时，不需要建立组播分发树，也不需要中间节点维护状态。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "【PPT思考题】IPv6组播MAC地址映射过程中，由于只映射了后32位，可能存在多对一的映射冲突。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "PIM-DM 运行机制中，周期性将流量扩散到全网的行为称为？", options: ["泛洪 (Flood)", "剪枝 (Prune)", "嫁接 (Graft)", "断路 (Assert)"], answer: [0] },
    { type: "single", title: "PIM-SM 模式中，第一跳路由器将源流量发给 RP 的方式是？", options: ["广播", "直接转发", "单播封装在注册报文中", "建立虚链路"], answer: [2] },
    { type: "single", title: "IPv6 组播地址前 8 位固定为？", options: ["FE80", "FC00", "FF", "2001"], answer: [2] },
    { type: "judge", title: "IPv6 地址 FF05::2 代表站点本地范围内的所有路由器。", options: ["正确", "错误"], answer: [0] },

    // === 模块九：QoS 服务质量（第9讲 & SDN.pdf） ===
    { type: "single", title: "【PPT原题】关于Priority Queuing (PQ) 队列调度算法的缺点，描述最准确的是？", options: ["无法保证高优先级带宽", "算法复杂度太高", "低优先级的报文可能得不到调度而“饿死”", "不支持语音"], answer: [2] },
    { type: "single", title: "【SDN.pdf】在 QoS 性能标准中，属于“准确度”范畴的参数是？", options: ["延时", "吞吐量", "错误概率 (Probability of error)", "抖动"], answer: [2] },
    { type: "single", title: "在 DiffServ 模型中，用于区分业务优先级并占用 6 位 Bit 的字段是？", options: ["IP Precedence", "DSCP", "Exp", "Label"], answer: [1] },
    { type: "single", title: "哪种队列算法可以分配带宽比，保证不同优先级业务的权值？", options: ["FIFO", "PQ", "WFQ (加权公平队列)", "RR"], answer: [2] },
    { type: "single", title: "QoS 参数中，“抖动 (Jitter)”的准确定义是？", options: ["报文丢失比例", "端到端最大延时", "延时的变化幅度", "吞吐量波动"], answer: [2] },
    { type: "multi", title: "QoS 的三大服务模型包括？", options: ["Best-Effort (尽力而为)", "IntServ (综合服务)", "DiffServ (区分服务)", "MPLS"], answer: [0, 1, 2] },
    { type: "multi", title: "常用的拥塞管理技术（队列调度）包括？", options: ["PQ", "CQ", "WFQ", "CBWFQ"], answer: [0, 1, 2, 3] },
    { type: "judge", title: "IntServ 模型由于需要 RSVP 协议在所有路径节点上维护流状态，因此扩展性较差。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "QoS 技术中的 PHB（逐跳行为）是在哪个模型中定义的？", options: ["Best-Effort", "IntServ", "DiffServ", "RSVP"], answer: [2] },
    { type: "multi", title: "常用的拥塞避免（Congestion Avoidance）技术包括？", options: ["Tail Drop", "WRED (加权随机早期检测)", "RED", "PQ"], answer: [0, 1, 2] },

    // === 模块十：SDN 软件定义网络（SDN.pdf 考点全覆盖） ===
    { type: "single", title: "【SDN.pdf】SDN 的核心架构特征是？", options: ["控制与转发合一", "控制与转发分离、逻辑集中控制", "基于分布式算法", "仅支持专用硬件"], answer: [1] },
    { type: "single", title: "【SDN.pdf】SDN 架构中，南向接口最典型的协议是？", options: ["OpenFlow", "BGP", "RESTful API", "SNMP"], answer: [0] },
    { type: "single", title: "【SDN.pdf】SDN 架构中，北向接口主要负责？", options: ["下发流表", "控制器与上层应用/业务编排层通信", "交换机互联", "监控物理链路"], answer: [1] },
    { type: "single", title: "【SDN.pdf】OpenFlow 中用于实现数据包高效克隆与多端口转发的表项是？", options: ["流表 (Flow Table)", "计量表 (Meter Table)", "组表 (Group Table)", "管道表"], answer: [2] },
    { type: "single", title: "【SDN.pdf】OpenFlow 计量表 (Meter Table) 的主要功能是？", options: ["转发数据", "限速与标记流量", "备份配置", "拓扑发现"], answer: [1] },
    { type: "judge", title: "【SDN.pdf】SDN 组播面临流表溢出攻击（TCAM Exhaustion）的安全挑战。", options: ["正确", "错误"], answer: [0] },

    // === 模块十一：IPv6+ 与新技术（综合自第1讲及后续） ===
    { type: "single", title: "SRv6 技术核心是利用了 IPv6 的哪种扩展报头？", options: ["HBH Header", "Fragment Header", "SRH (Segment Routing Header)", "AH Header"], answer: [2] },
    { type: "single", title: "SRv6 中的 SID（Segment Identifier）长度是多少位？", options: ["32位", "64位", "128位", "256位"], answer: [2] },
    { type: "multi", title: "IPv6+ 技术体系主要包含下列哪些创新技术？", options: ["SRv6", "网络切片", "随流检测 (iFIT)", "BIERv6"], answer: [0, 1, 2, 3] },
    { type: "judge", title: "IPv6+ 使得网络不仅具备连接能力，更具备了可编程和业务感知能力。", options: ["正确", "错误"], answer: [0] },

    // === 模块十二：补遗与细节考点（确保满 120 题） ===
    { type: "single", title: "IPv6 报头中 Payload Length 字段的长度是多少位？", options: ["8", "16", "20", "32"], answer: [1] },
    { type: "single", title: "OSPFv3 协议中，哪一类 LSA 用于通告 AS 外部路由？", options: ["Type 3", "Type 4", "Type 5", "Type 7"], answer: [2] },
    { type: "single", title: "BGP 选路中，Local_Preference 越大越优先还是越小越优先？", options: ["越大越优先", "越小越优先", "两者均可", "不影响"], answer: [0] },
    { type: "single", title: "ICMPv6 目标不可达消息的消息类型 (Type) 是？", options: ["1", "2", "3", "4"], answer: [0] },
    { type: "single", title: "IPv6 的 Anycast 地址（任播地址）主要是为了提供？", options: ["一对多通信", "一对一通信", "一对最近通信", "多对多通信"], answer: [2] },
    { type: "single", title: "BGP 的 MED 属性默认值是多少？", options: ["0", "1", "100", "255"], answer: [0] },
    { type: "single", title: "ICMPv6 报文中，Type=135 对应哪种 NDP 报文？", options: ["RS", "RA", "NS", "NA"], answer: [2] },
    { type: "single", title: "OSPF 建立毗邻关系时，如果掩码不一致，在广播网中会如何？", options: ["正常建立", "无法建立", "部分建立", "忽略掩码"], answer: [1] },
    { type: "judge", title: "IPv6 无状态地址自动配置不需要 DHCP 服务器参与。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "IPv6 动态路由协议 RIPng 使用的端口号是？", options: ["520", "521", "179", "89"], answer: [1] },
    { type: "single", title: "BGP 中的 MED 属性主要用于告知邻居 AS 进入本 AS 的首选路径。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "BGP 选路中，Router-ID 越小的邻居越优先。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "OSPFv3 中 LSA 类型的 LS Type 取值 0x2001 代表？", options: ["Router-LSA", "Network-LSA", "Link-LSA", "Intra-Area-Prefix-LSA"], answer: [0] },
];