const bank = [
    { type: "single", title: "距离矢量路由选择协议的基本原理包括哪些步骤？", options: ["定期向邻居发送路由更新", "仅在拓扑变化时发送更新", "使用SPF算法", "维护全网拓扑"], answer: [0] },
    { type: "single", title: "在RIPng中，下一跳地址和源地址通常使用哪种类型的IPv6地址？", options: ["全球单播地址", "链路本地地址", "站点本地地址", "任播地址"], answer: [1] },
    { type: "single", title: "动态路由协议相比静态路由在大型网络中的主要优势是什么？", options: ["能够自动适应网络拓扑的变化", "配置更简单", "占用资源更少", "转发速度更快"], answer: [0] },
    { type: "single", title: "配置黑洞接口null的主要作用是什么？", options: ["防止路由环路", "加速转发", "增加带宽", "加密传输"], answer: [0] },
    { type: "single", title: "路由汇总的目的是什么？", options: ["减少路由表的大小", "提高匹配精度", "增加收敛时间", "防止攻击"], answer: [0] },
    { type: "single", title: "OSPF的Hello报文的主要作用是什么？", options: ["发现和维护邻居关系", "传输链路状态更新", "计算最短路径树", "确认LSA信息"], answer: [0] },
    { type: "single", title: "在OSPF中，哪种类型的路由器可以同时属于多个区域？", options: ["区域边界路由器 (ABR)", "自治系统边界路由器 (ASBR)", "内部路由器", "骨干路由器"], answer: [0] },
    { type: "single", title: "BGP协议能够避免路由环路是因为什么？", options: ["在路由的AS-Path属性中记录着所有途经的AS", "基于链路状态算法", "使用跳数限制", "强制物理直连"], answer: [0] },
    { type: "single", title: "BGP运行在哪里？", options: ["自治系统 (AS) 之间", "路由器内部", "交换机之间", "物理链路上"], answer: [0] },
    { type: "single", title: "BGP的哪种报文用于通知对端BGP运行中发生错误？", options: ["Notification报文", "Update报文", "Keepalive报文", "Open报文"], answer: [0] },
    { type: "single", title: "在BGP状态机中，哪种状态表示TCP连接已成功建立？", options: ["OpenSent", "Active", "Established", "Connect"], answer: [2] },
    { type: "single", title: "BGP的哪种属性用于描述路由的来源？", options: ["Origin属性", "AS_Path", "Next_Hop", "MED"], answer: [0] },
    { type: "single", title: "BGP的哪种属性用于选择离开本AS的最佳出口？", options: ["Local_Pref", "MED", "Community", "Origin"], answer: [0] },
    { type: "single", title: "BGP的哪种对等体关系存在于不同AS之间？", options: ["EBGP", "IBGP", "IGP", "RIP"], answer: [0] },
    { type: "single", title: "OSPFv3中，哪个参数用于区分同一个接口上的不同OSPF实例？", options: ["Instance ID", "Process ID", "Area ID", "Interface ID"], answer: [0] },
    { type: "single", title: "OSPF中的LSAck报文的作用是什么？", options: ["确认收到LSA信息", "请求丢失的LSA", "描述数据库摘要", "选举DR"], answer: [0] },
    { type: "single", title: "在OSPF中，哪种报文用于选举DR和BDR？", options: ["Hello报文", "DD报文", "LSR报文", "LSU报文"], answer: [0] },
    { type: "single", title: "OSPF中的BDR的作用是什么？", options: ["当DR失效时接替其工作", "负责所有路由更新", "仅在P2P链路存在", "增加洪泛"], answer: [0] },
    { type: "single", title: "OSPF中的区域的主要用途是什么？", options: ["限制路由信息的传播范围，减少计算量", "增加CPU负荷", "允许IP重叠", "强制经过Area 1"], answer: [0] },
    { type: "single", title: "在OSPF中，如果Hello间隔为10s，Dead间隔默认为？", options: ["40s", "20s", "30s", "60s"], answer: [0] },
    { type: "single", title: "OSPF中的SPF算法的目的是什么？", options: ["计算最短路径树", "建立TCP邻居", "发现邻居", "压缩路由表"], answer: [0] },
    { type: "single", title: "OSPFv3的Router-ID长度是多少位？", options: ["32位", "48位", "64位", "128位"], answer: [0] },
    { type: "single", title: "OSPF协议运行在IP层之上，协议号是？", options: ["89", "88", "179", "6"], answer: [0] },
    { type: "single", title: "RIPng使用的传输层端口号是多少？", options: ["UDP 521", "UDP 520", "TCP 179", "TCP 89"], answer: [0] },
    { type: "single", title: "RIP协议属于哪类路由协议？", options: ["距离矢量", "链路状态", "路径矢量", "混合"], answer: [0] },
    { type: "single", title: "静态路由配置中，使用接口和使用地址的主要差别是什么？", options: ["使用接口不需要解析下一跳MAC", "使用地址不需要查询路由表", "使用接口更安全", "没有差别"], answer: [0] },
    { type: "single", title: "静态路由适用于以下哪种网络环境？", options: ["简单的、小型且拓扑结构稳定的网络", "大型跨国网络", "运营商核心网", "频繁变动的网络"], answer: [0] },
    { type: "single", title: "路由表中的路由来源不包括？", options: ["直连路由", "静态路由", "动态路由", "ARP缓存"], answer: [3] },
    { type: "single", title: "OSPF中的DR的作用是什么？", options: ["减少区域内的邻接关系数量", "计算最短路径", "负责跨区域转发", "作为默认网关"], answer: [0] },
    { type: "single", title: "BGP默认使用的TCP端口是？", options: ["179", "520", "89", "443"], answer: [0] },
    { type: "single", title: "什么是AS（自治系统）？", options: ["拥有统一路由策略的一组路由器的集合", "局域网", "IP地址池", "服务器集群"], answer: [0] },
    { type: "single", title: "BGP的哪种报文用于维持邻居关系？", options: ["Keepalive报文", "Update", "Open", "Notification"], answer: [0] },
    { type: "single", title: "BGP的哪种属性用于记录途经的AS序列？", options: ["AS_Path属性", "Origin", "Next_Hop", "MED"], answer: [0] },
    { type: "single", title: "BGP的哪种邻居关系在同一个AS内部？", options: ["IBGP", "EBGP", "IGP", "EGP"], answer: [0] },
    { type: "single", title: "OSPF中的Area 0通常被称为？", options: ["骨干区域", "末梢区域", "标准区域", "虚拟区域"], answer: [0] },
    { type: "single", title: "在OSPF中，Full状态表示？", options: ["链路状态数据库已同步", "正在交换Hello", "正在选举DR", "物理链路中断"], answer: [0] },
    { type: "single", title: "BGP选路原则中，Local_Preference越高越？", options: ["优", "劣", "没影响", "视情况而定"], answer: [0] },
    { type: "single", title: "BGP的Next_Hop属性描述？", options: ["到达目的地的下一跳IP", "起源AS", "路由代价", "团体属性"], answer: [0] },
    { type: "single", title: "OSPF中，LSU报文包含？", options: ["具体的LSA信息", "摘要信息", "请求信息", "确认信息"], answer: [0] },
    { type: "single", title: "静态路由中，浮动路由主要通过修改什么实现？", options: ["管理距离 (Administrative Distance)", "度量值 (Metric)", "接口带宽", "优先级"], answer: [0] },
    { type: "multi", title: "OSPF中的哪些区域类型可以接收外部路由（Type 5 LSA）信息？", options: ["骨干区域 (Area 0)", "标准区域", "Stub区域", "Totally Stub区域"], answer: [0, 1] },
    { type: "multi", title: "OSPF的哪些报文类型直接用于链路状态数据库的同步？", options: ["Hello报文", "DD报文", "LSR报文", "LSU报文"], answer: [1, 2, 3] },
    { type: "multi", title: "BGP注入路由的方式有哪些？", options: ["network命令", "import-route重分布", "ARP学习", "ICMP重定向"], answer: [0, 1] },
    { type: "multi", title: "BGP公认必遵属性包括？", options: ["Origin", "AS_Path", "Next_Hop", "MED"], answer: [0, 1, 2] },
    { type: "multi", title: "OSPFv3相比OSPFv2的变化包括？", options: ["移除了LSA中IP地址依赖", "支持多实例", "取消了Router ID", "改变了SPF算法"], answer: [0, 1] },
    { type: "judge", title: "BGP聚合（Aggregation）功能可以减少路由表的大小。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "BGP的Community属性是可选过渡属性。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "从IBGP邻居学到的路由，BGP路由器会将其通告给其他IBGP邻居。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "BGP路由器默认开启同步（Synchronization）功能以防止路由黑洞。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "OSPF中的DR选举是不可抢占的。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "BGP的哪种报文用于宣告接收动态刷新路由的能力？", options: ["Route-Refresh报文", "Open报文", "Update报文", "Notification报文"], answer: [0] },
    { type: "single", title: "BGP的哪种属性用于描述路由的团体，用于选择或过滤？", options: ["Community属性", "MED属性", "Origin属性", "AS_Path属性"], answer: [0] },
    { type: "single", title: "BGP协议能够避免路由环路是因为什么？", options: ["利用AS_Path属性检查自己的AS号", "利用跳数限制", "利用SPF算法", "利用建立邻居时的密码"], answer: [0] },
    { type: "single", title: "在BGP中，如果从EBGP获得的路由，它会向哪些邻居通告？", options: ["所有的IBGP和EBGP邻居", "仅IBGP邻居", "仅EBGP邻居", "不通告"], answer: [0] },
    { type: "single", title: "BGP的哪种属性用于施加影响，引导出口流量？", options: ["Local_Pref", "MED", "Origin", "Next_Hop"], answer: [0] },
    { type: "single", title: "BGP的哪种属性用于描述路由的多出口识别，且仅影响上游？", options: ["MED属性", "Local_Pref", "AS_Path", "Community"], answer: [0] },
    { type: "single", title: "在BGP中，Keepalive报文的主要作用是什么？", options: ["维持邻居关系并告知路由器存活", "传输路由更新", "建立TCP连接", "报告错误"], answer: [0] },
    { type: "single", title: "BGP选路原则中，权重最高的属性通常是？", options: ["Preferred-Value", "Local_Pref", "AS_Path", "Origin"], answer: [0] },
    { type: "single", title: "组播组用哪一类IP地址来标识？", options: ["D类IP地址", "A类", "B类", "C类"], answer: [0] },
    { type: "single", title: "以下哪个知名组播地址是所有主机群组的IP组播地址？", options: ["224.0.0.1", "224.0.0.2", "224.0.0.5", "224.0.0.13"], answer: [0] },
    { type: "single", title: "私人组播地址空间的范围是多少？", options: ["239.0.0.0 到 239.255.255.255", "224.0.0.0 到 224.0.0.255", "232.0.0.0/8", "233.0.0.0/8"], answer: [0] },
    { type: "single", title: "以下哪个协议是IP协议簇中负责组播组成员管理的协议？", options: ["IGMP", "PIM", "MSDP", "MBGP"], answer: [0] },
    { type: "single", title: "IGMPv3相比于IGMPv2增加了哪个功能？", options: ["支持指定信源组播 (SSM)", "支持离开组消息", "支持查询者选举", "支持查询最大响应时间"], answer: [0] },
    { type: "single", title: "以下哪个协议是第一个基于距离矢量的组播路由协议？", options: ["DVMRP", "PIM-DM", "PIM-SM", "MOSPF"], answer: [0] },
    { type: "single", title: "以下哪个协议是协议无关组播？", options: ["PIM", "DVMRP", "MOSPF", "CBT"], answer: [0] },
    { type: "single", title: "PIM-SM使用哪种类型的树来发送和接收组播数据？", options: ["共享树 (RPT) 与有源树 (SPT) 结合", "仅有源树", "仅共享树", "最短路径树"], answer: [0] },
    { type: "single", title: "在PIM-SM中，发送者和接收者在共享树中汇聚的点被称为？", options: ["汇聚点 (RP)", "BSR", "DR", "源点"], answer: [0] },
    { type: "single", title: "在PIM-SM中，当源的DR建立起（S,G）项时，意味着？", options: ["开始向RP发送注册报文", "组播分发完成", "邻居建立完成", "DR选举完成"], answer: [0] },
    { type: "single", title: "一个系统采用有源树，50个源向10个组播组推送数据，最多有多少棵不同的树？", options: ["500棵", "50棵", "10棵", "60棵"], answer: [0] },
    { type: "single", title: "在IPv4中，组播地址224.66.60.89映射到以太网的地址是什么？", options: ["01:00:5E:42:3C:59", "01:00:5E:42:3C:58", "00:00:5E:42:3C:59", "33:33:42:3C:59"], answer: [0] },
    { type: "single", title: "IPv4组播地址239.192.168.10映射到以太网的地址是什么？", options: ["01:00:5E:40:A8:0A", "01:00:5E:C0:A8:0A", "01:00:5E:40:A8:0B", "33:33:C0:A8:0A"], answer: [0] },
    { type: "single", title: "在IPv6中，组播地址FF02::1映射到以太网的地址是什么？", options: ["33:33:00:00:00:01", "01:00:5E:00:00:01", "33:33:FF:00:00:01", "33:33:00:00:00:02"], answer: [0] },
    { type: "single", title: "IPv6组播地址映射中，MAC地址是如何生成的？", options: ["将IPv6地址后32位直接映射，并加上33-33前缀", "映射后24位", "随机生成", "使用前缀01-00-5E"], answer: [0] },
    { type: "single", title: "在IPv6知名组播地址中，哪个是链路本地范围的所有路由器的组播地址？", options: ["FF02::2", "FF02::1", "FF01::1", "FF05::2"], answer: [0] },
    { type: "single", title: "OSPF中的Stub区域的主要特点是什么？", options: ["不接收外部路由，通过默认路由到达外部", "接收所有路由", "不接收区域间路由", "仅接收Type 7 LSA"], answer: [0] },
    { type: "single", title: "在OSPF中，哪种报文用于请求特定的LSA信息？", options: ["LSR报文", "LSU报文", "DD报文", "Hello报文"], answer: [0] },
    { type: "single", title: "OSPF中的LSA（链路状态通告）的主要内容是？", options: ["路由器的链路状态信息、度量值等", "全网路由表", "邻居密码", "用户的ARP表"], answer: [0] },
    { type: "single", title: "OSPF中的Router ID是如何确定的？", options: ["手动配置优于自动选择", "自动选择最大IP", "随机生成", "由DR分配"], answer: [0] },
    { type: "single", title: "在OSPF中，哪种类型的路由器所有接口都在同一个区域内？", options: ["Internal Router", "ABR", "ASBR", "Backbone Router"], answer: [0] },
    { type: "single", title: "在BGP中，哪种消息用于交换路由信息？", options: ["Update报文", "Open报文", "Keepalive报文", "Notification报文"], answer: [0] },
    { type: "multi", title: "IP组播的优势包括哪些？", options: ["节省带宽", "减轻发送者负担", "减轻网络资源消耗", "提高传输绝对安全性"], answer: [0, 1, 2] },
    { type: "multi", title: "以下哪些是IGMPv3相比于IGMPv1的新特征？", options: ["支持离开组消息", "支持特定源组播", "支持查询者选举机制", "支持广播抑制"], answer: [0, 1, 2] },
    { type: "multi", title: "以下哪些IP组播地址映射到相同的以太网地址？", options: ["224.1.1.1 与 225.1.1.1", "224.0.0.1 与 224.0.0.2", "239.1.1.1 与 238.1.1.1", "224.1.1.1 与 224.1.1.2"], answer: [0, 2] },
    { type: "multi", title: "以下哪些是PIM-DM的特点？", options: ["采用扩散-剪枝机制", "适用于成员密集的网络", "构建有源树", "需要RP"], answer: [0, 1, 2] },
    { type: "multi", title: "PIM-SM与PIM-DM相比，有哪些不同？", options: ["PIM-SM使用RP", "PIM-SM构建共享树", "PIM-SM采用拉模型", "PIM-DM支持IPv6"], answer: [0, 1, 2] },
    { type: "multi", title: "在PIM-SM中，以下哪些是共享树剪枝的必要条件？", options: ["本地无接收者", "下游接口为空", "收到来自上游的剪枝消息", "BSR失效"], answer: [0, 1] },
    { type: "multi", title: "在IPv6组播中，以下哪些是MLD的特点？", options: ["基于ICMPv6", "用于发现邻居接收者", "功能类似IGMP", "运行在TCP上"], answer: [0, 1, 2] },
    { type: "multi", title: "BGP属性中，哪些属于公认必遵属性？", options: ["Origin", "AS_Path", "Next_Hop", "MED"], answer: [0, 1, 2] },
    { type: "multi", title: "关于BGP AS_Path属性，以下说法正确的是？", options: ["用于防环", "用于选路（路径短者优）", "仅在EBGP间通告", "必须手动配置"], answer: [0, 1] },
    { type: "multi", title: "BGP社区 (Community) 属性的作用包括？", options: ["标记路由", "简化策略实施", "计算跳数", "建立邻居"], answer: [0, 1] },
    { type: "judge", title: "BGP聚合路由时，AS_Path属性总是被丢失。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "BGP的MED属性是可选非过渡属性。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "OSPFv3协议直接运行在IPv6报文之上，协议号为89。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "PIM-DM协议采用“推”模型来传输组播数据。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "在PIM-SM中，所有源和接收者必须通过汇聚点（RP）进行通信。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "IPv6组播协议MLDv1完全对应于IGMPv1的功能。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "BGP的Next_Hop属性在通告给IBGP邻居时默认不改变。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "OSPF中的DR选举是不可抢占的。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "BGP选路时会先看Local_Pref再看AS_Path。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "OSPFv3的Router ID必须手动配置。", options: ["正确", "错误"], answer: [0] },
    { type: "single", title: "RSVP是综合服务模型的核心，其全称是？", options: ["ReSource ReserVation Protocol", "Remote Session Protocol", "Real-time Streaming Protocol", "Reliable Sockets Protocol"], answer: [0] },
    { type: "single", title: "在区分服务模型（DiffServ）中，EF代表什么？", options: ["Expedited Forwarding", "Enhanced Forwarding", "Economic Forwarding", "Efficient Forwarding"], answer: [0] },
    { type: "single", title: "实时视频交互应用中，最应关注的QoS指标是？", options: ["延时与抖动", "吞吐量", "可靠性", "队列长度"], answer: [0] },
    { type: "single", title: "QoS中哪个参数与数据传输的可靠性最相关？", options: ["丢包率", "带宽", "延时", "抖动"], answer: [0] },
    { type: "single", title: "MPLS标签头部总共有多少个比特？", options: ["32 bits", "20 bits", "64 bits", "128 bits"], answer: [0] },
    { type: "single", title: "DSCP码点应分别搭载到IPv4和IPv6头部的哪个字段？", options: ["ToS和Traffic Class", "TTL和Hop Limit", "Protocol和Next Header", "Flow Label"], answer: [0] },
    { type: "single", title: "以下哪个不是拥塞避免技术？", options: ["FIFO", "WRED", "RED", "Tail Drop"], answer: [0] },
    { type: "single", title: "在IPv6知名组播地址中，哪个是所有路由器的组播地址？", options: ["FF02::2", "FF02::1", "FF01::1", "FF05::2"], answer: [0] },
    { type: "single", title: "IPv6组播地址映射中，MAC地址的前缀是？", options: ["33-33", "01-00-5E", "00-00-5E", "FF-FF"], answer: [0] },
    { type: "single", title: "PIM-SM中建立有源树（SPT）的标志是？", options: ["建立(S,G)表项", "建立(*,G)表项", "选举出DR", "收到Hello报文"], answer: [0] },
    { type: "multi", title: "QoS的核心参数包括哪些？", options: ["带宽", "延时", "抖动", "丢包率"], answer: [0, 1, 2, 3] },
    { type: "multi", title: "以下哪些属于常见的队列调度技术？", options: ["FIFO", "PQ", "WFQ", "CQ"], answer: [0, 1, 2, 3] },
    { type: "multi", title: "在区分服务模型 (DiffServ) 中，常见的服务类别包括？", options: ["EF (快速转发)", "AF (确保转发)", "BE (尽力而为)", "CS (类选择器)"], answer: [0, 1, 2, 3] },
    { type: "multi", title: "MPLS 的特点包括哪些？", options: ["支持流量工程 (TE)", "支持VPN业务", "转发速度快", "基于IP首部逐跳转发"], answer: [0, 1, 2] },
    { type: "multi", title: "IPv6 组播地址的 Scope 字段可以指明哪些范围？", options: ["节点本地范围", "链路本地范围", "站点范围", "全球范围"], answer: [0, 1, 2, 3] },
    { type: "multi", title: "以下关于 PIM-DM 剪枝条件的描述，正确的是？", options: ["路由器没有下游邻居", "所有叶网络上没有组成员", "收到上游查询报文", "接口带宽过低"], answer: [0, 1] },
    { type: "multi", title: "在 IPv6 组播中，BIER 技术的特点包括？", options: ["基于比特索引的显式复制", "中间路由器无需维护组播树状态", "必须依赖汇聚点RP", "简化了控制面"], answer: [0, 1, 3] },
    { type: "multi", title: "路由表条目的来源通常包括？", options: ["直连路由", "静态路由", "动态路由", "MAC地址表"], answer: [0, 1, 2] },
    { type: "multi", title: "在OSPF中，哪些因素可能影响路由的选择？", options: ["路径开销Cost", "区域类型(内优于外)", "Router ID", "邻居数量"], answer: [0, 1] },
    { type: "multi", title: "OSPF的哪些报文类型直接用于LSDB的同步？", options: ["DD报文", "LSR报文", "LSU报文", "Hello报文"], answer: [0, 1, 2] },
    { type: "judge", title: "区分服务（DiffServ）模型需要为每个流维护单独的状态信息。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "综合服务模型（IntServ）依赖于RSVP协议进行资源预留。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "MPLS的标签位于网络层（第三层）的头部。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "加权公平队列（WFQ）通过IP优先级分配带宽。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "在IP报文中，DSCP字段占用IPv4头部中ToS字段的全部8个比特。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "IPv6中没有广播，只有组播。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "BGP聚合路由时，AS_Path属性总是被丢失。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "PIM-DM协议采用“推”模型来传输组播数据。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "OSPFv3的Router ID必须手动配置。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "BGP的MED属性是可选过渡属性。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "OSPF中的DR选举是不可抢占的。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "RIPv1协议支持VLSM和CIDR。", options: ["正确", "错误"], answer: [1] },
    { type: "judge", title: "BGP连接建立前，双方必须先完成TCP三次握手。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "静态路由的优先级总是高于动态路由。", options: ["正确", "错误"], answer: [1] },
    { type: "single", title: "BGP选路原则中，如果Local_Pref相同，则优选？", options: ["AS_Path最短的", "Router ID最小的", "MED最大的", "Origin最高的"], answer: [0] },
    { type: "single", title: "OSPF协议中，Type 2 LSA是由谁生成的？", options: ["DR (指定路由器)", "ABR", "ASBR", "所有路由器"], answer: [0] },
    { type: "single", title: "在BGP中，Local_Preference属性只在什么范围内传播？", options: ["AS内部", "AS之间", "仅限邻居", "全球范围"], answer: [0] },
    { type: "single", title: "IPv4组播地址的前4位固定为？", options: ["1110", "1100", "1010", "1111"], answer: [0] },
    { type: "single", title: "MPLS网络中，负责根据标签转发数据的设备称为？", options: ["LSR (标签交换路由器)", "LER", "CE", "PE"], answer: [0] },
    { type: "single", title: "下列哪种技术可以解决BGP路由黑洞问题？", options: ["全互联或MPLS", "水平分割", "毒性逆转", "提高带宽"], answer: [0] },
    { type: "multi", title: "关于BGP AS_Path属性，说法正确的是？", options: ["用于防环", "选路时长度短者优", "IBGP间传递不改变", "EBGP间传递会添加本地AS"], answer: [0, 1, 2, 3] },
    { type: "judge", title: "IGMPv2通过最大响应时间来控制成员报告抑制。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "PIM-SM共享树上的流量是以RP为根分发的。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "RIP协议的最大跳数为15，16跳表示不可达。", options: ["正确", "错误"], answer: [0] },
    { type: "judge", title: "BGP状态机中，Active状态表示TCP连接尝试失败并正在重试。", options: ["正确", "错误"], answer: [0] }
]; 
